permissions:
  contents: write
name: Build Design Tokens

on:
  push:
    branches: [main]
    paths:
      - 'tokens.json'
      - 'style-dictionary.config.*'

  workflow_dispatch:
    inputs:
      reason:
        description: "Kenapa di-run manual"
        required: false
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: npm run build:all
  
      - name: Commit build result
        run: |
          git config --global user.name "mamang-color"
          git config --global user.email "mamang-color@uayuex.com"

          git add build

          if git diff --cached --quiet; then
            echo "No changes"
            exit 0
          fi

          git commit -m "auto build tokens"

          git pull --rebase origin main   # 🔥 WAJIB

          git push

    #    # 7. Clone UI repo
    #   - name: Clone UI repo
    #     run: |
    #       git clone https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/Rickyarians/React-UI-Component-Base.git

    #   # 8. Copy theme ke UI repo
    #   - name: Copy theme file
    #     run: |
    #       cp semantic/react/theme.ts React-UI-Component-Base/theme/theme.ts

    #   # 9. Commit & push ke branch baru
    #  - name: Commit & Push to UI repo
    #     run: |
    #       cd React-UI-Component-Base

    #       BRANCH=update-theme-${{ github.run_id }}

    #       git checkout -b $BRANCH

    #       git config user.name "token-bot"
    #       git config user.email "token-bot@bot.com"

    #       git add src/theme/theme.ts

    #       if git diff --cached --quiet; then
    #         echo "No changes in theme"
    #         exit 0
    #       fi

    #       git commit -m "chore: update theme from design tokens"
    #       git pull origin main
    #       git push origin $BRANCH

    #   # 10. Create PR
    #   - name: Create Pull Request
    #     run: |
    #       curl -X POST https://api.github.com/repos/Rickyarians/ui-React-UI-Component-Base/pulls \
    #       -H "Authorization: token ${{ secrets.PAT_TOKEN }}" \
    #       -H "Accept: application/vnd.github+json" \
    #       -d '{
    #         "title": "Update theme from design tokens",
    #         "head": "update-theme-${{ github.run_id }}",
    #         "base": "main",
    #         "body": "Auto-generated from design tokens 🚀"
    #       }'
