name: Build Design Tokens

on:
  push:
    branches: [main]
    paths:
      - 'tokens.json'
      - 'style-dictionary.config.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Build tokens
        run: npm run build
      
      - name: Commit build result
        run: |
          git config --global user.name "mamang-color"
          git config --global user.email ""mamang-color@uayuex.com"
          git add build
          git commit -m "auto build tokens" || echo "No changes"
          git push
